name: 'Verify Adventure'
on:
  workflow_dispatch:
    inputs:
      challenge:
        description: The challenge to verify
        required: true
        type: choice
        options:
          - '游깭 Adventure 02 | 游릭 Beginner (The Foundation Stones)'
          - 'Adventure 01 | 游댮 Expert (Hyperspace Operations and Transport)'
          - 'Adventure 01 | 游리 Intermediate (The Silent Canary)'
          - 'Adventure 01 | 游릭 Beginner (Broken Echoes)'
jobs:
  adventure02-beginner:
    name: '游깭 Adventure 02 | 游릭 Beginner (The Foundation Stones)'
    if: ${{ inputs.challenge == '游깭 Adventure 02 | 游릭 Beginner (The Foundation Stones)' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dynatrace-oss/open-ecosystem-challenge-verifier@main
        with:
          challenge: '02-building-cloudhaven_beginner'
  easy:
    name: 'Adventure 01 | 游릭 Beginner (Broken Echoes)'
    if: ${{ inputs.challenge == 'Adventure 01 | 游릭 Beginner (Broken Echoes)' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dynatrace-oss/open-ecosystem-challenge-verifier@main
        with:
          challenge: '01-echoes-lost-in-orbit_beginner'
  intermediate:
    name: 'Adventure 01 | 游리 Intermediate (The Silent Canary)'
    if: ${{ inputs.challenge == 'Adventure 01 | 游리 Intermediate (The Silent Canary)' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dynatrace-oss/open-ecosystem-challenge-verifier@main
        with:
          challenge: '01-echoes-lost-in-orbit_intermediate'
  expert:
    name: 'Adventure 01 | 游댮 Expert (Hyperspace Operations and Transport)'
    if: ${{ inputs.challenge == 'Adventure 01 | 游댮 Expert (Hyperspace Operations and Transport)' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dynatrace-oss/open-ecosystem-challenge-verifier@main
        with:
          challenge: '01-echoes-lost-in-orbit_expert'